### PR TITLE
Specsheets

### LINKED ISSUE #25: Is there any plan to have Tyro on Cocoapods, like Swiftz?

### PR DESCRIPTION
**Pull request by CodaFi**
- Rounds out the Xcode project schemes with a tvOS scheme
- Adds a podspec (fixes #25).

### CODE REVIEW

**Comment by mpurland** [comment]
👍

**Comment by mpurland** [comment]
@CodaFi Need to add Swiftz as a dependency in the podspec

**Comment by CodaFi** [comment]
Yep.  Gotcha.

**Comment by mpurland** [comment]
@CodaFi 

In the build:

 /Users/travis/build/typelift/Tyro/TyroTests/DecimalNumberSpec.swift:10:8: module file's minimum deployment target is ios9.3 v9.3: /Users/travis/Library/Developer/Xcode/DerivedData/Tyro-azqwlkbpeursrpbtwqycbxyemvhz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Swiftz.framework/Modules/Swiftz.swiftmodule/x86_64.swiftmodule

Is it because Swiftz has a min version of iOS 9.3?

**Comment by CodaFi** [comment]
Eh, probably.  I'll see what I can do.

**Comment by CodaFi** [comment]
Weird, Swiftz has a min version of 8.0

**Comment by CodaFi** [comment]
Yay!

**Comment by CodaFi** [comment]
⛵

**Comment by mpurland** [comment]
👍

**Comment by mpurland** [comment]
@CodaFi Have you published the pod spec to CocoaPods yet? I'm not seeing it. I can do it if you want.

**Comment by CodaFi** [comment]
I did but this thing broke the build.  How the hell did this pass the first time?

**Pull request merged**
