### PR TITLE
Updated for Swift 2.2

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by CodaFi** [comment]
7.3 demands extraneous code signing stuff for no reason.  If you can build with carthage instead for the iOS scheme you'll be fine.

**Comment by mpurland** [comment]
How did you get around it for Swiftz?

**Comment by mpurland** [comment]
@CodaFi From Swiftz, in .travis.yml:  if [[ "$TEST_CONFIG" == "RELEASE" ]]; then script/cibuild Swiftz ; fi 

So, iOS isn't being built right now?

**Comment by CodaFi** [comment]
I'm assuming pods is building us there now.  I could be wrong.

**Comment by mpurland** [comment]
In order to get around I changed the cibuild to only build Tyro, not Tyro-iOS.

**Comment by mpurland** [comment]
@CodaFi I could be wrong, but it looks like based on the Travis CI logs that iOS is indeed not being tested for Swiftz either. 

If you're referring to the PODS test configuration then it simply does pod lib lint: https://travis-ci.org/typelift/Swiftz/jobs/118125955

**Comment by mpurland** [comment]
@CodaFi I think I may have found a slightly better way using xcodebuild.

**Comment by CodaFi** [comment]
Yeah, we need to extend this approach across the rest of TypeLift.  Thanks for the script.  It worked really well until the tools decided to change shape out from under us again.

**Comment by mpurland** [comment]
Yes. We never know what new workarounds are ahead us for each release of Xcode / iOS / OS X.

**Comment by mpurland** [comment]
Going to merge this PR. I think everything looks good unless there's anything else.

**Comment by CodaFi** [comment]
LGTM :+1: 

Merge when ready.

**Comment by mpurland** [comment]
:boat:

**Pull request merged**
